### ISSUE TITLE
Backsnap roadmap

### ISSUE THREAD

**Issue by sgielen** [skybitsnl/backsnap#1]
For the next version(s), I'd like to implement:

- [x] configuring a max number of backup jobs to run simultaneously (v0.3.0)
- [x] allow configuring constraints for the restore Pod, e.g. to bind it to a particular node or availability zone (v0.9.0)
- [ ] provide a method to list which snapshots exist for a backup, so that it becomes easier to perform a point-in-time restore (also document this process)
- [ ] write "cluster migration" use-case documentation
- [ ] allow refreshing the restic password (i.e. configuring multiple restic keys at the same time)
- [ ] allow configuring the backup PVC AccessMode for CSIs that support it
- [ ] allow configuring retention policies per namespace / PVC
- [ ] perform additional e2e testing against a matrix of Kubernetes versions
- [ ] implement metrics and suggest alerts
- [ ] also back up CR object YAMLs in the namespace, so as to become a light alternative to velero
- [ ] warn about backups that exist on S3 that don't have PVCs anymore

Please feel encouraged to submit additional suggestions. If you'd like to take on any of these, please let me know as well and I'll support you and make sure we don't waste time working on the same thing.
